### ISSUE TITLE
What actually triggers this web extension to get installed without consent?

### ISSUE THREAD

**Issue by Gitoffthelawn** [mozilla-extensions/restore-search-defaults#22]
What actually triggers this web extension to get automatically installed within Firefox?  How can the automatic forced-installation of this web extension be disabled?

The automatic installation of this extension causes some security systems to throw up a big red flag and issue critical alerts every time this web extension gets force-installed in any Firefox profile.  These alerts are by design, and not a problem with the security software.  It is correctly issuing alerts that executable code was downloaded and installed without consent.

Also, I was wondering the meaning of this pref:
```
extensions.reset_default_search.runonce.reason
```

What does `previousRun` indicate for its value on a brand new Firefox profile and why is that specified as a reason for installation?

Similarly what does `noAddonsEligible` really indicate as a value?

Thank you for your time.

**Comment by mixedpuppy** [comment]
noAddonsEligible means you do not have addons installled that this addon is addressing an issue for.  Once the prefs are set, the addon will not do anything.  This addon is installed through one of our update mechanisms used to push updates between releases.

If you want to disable our updates you can flip the pref extensions.systemAddon.update.enabled, but it does mean you wouldn't get something that might be important [moreso than this particular addon].

**Comment by Gitoffthelawn** [comment]
@mixedpuppy Thanks Shane.

So is this pushed to 100% of Firefox profiles?

If so, why is this a web extension and not just part of Firefox?

What does the `previousRun` value indicate as a `reason`?

From what I've seen, this web extension will get force-installed in Firefox profiles at seemingly random times, then get force-deleted at seemingly random times, then get force-installed again sometime after Firefox gets updated (even for minor updates), then get force-deleted again, ad infinitum. Although I imagine the times aren't actually random, is this the overall designed behaviour and UX?
