### ISSUE TITLE
Can this system add-on be distributed like other system add-ons?

### ISSUE THREAD

**Issue by Gitoffthelawn** [mozilla-extensions/restore-search-defaults#23]
Firefox, by default, is distributed with a number of system add-ons, including:

```
doh-rollout@mozilla.org.xpi
formautofill@mozilla.org.xpi
pictureinpicture@mozilla.org.xpi
screenshots@mozilla.org.xpi
webcompat@mozilla.org.xpi
webcompat-reporter@mozilla.org.xpi
```

Would it be possible to distribute this add-on in the same manner as all of those other system add-ons (located in the `browser\features` folder within the folder containing Firefox's executable)?

I know Mozilla strives for simplicity, so it seems in line with that goal to have all system add-ons distributed and installed using a single model.  (BTW, a little LOL: I initially wrote `in line` as `inline`... too much time spent coding recently!  Maybe Google's reCaptcha's are on to something, and I *am* a robot!)

**Comment by kewisch** [comment]
Thanks for getting in touch! This add-on is not being deployed on the regular Firefox release schedule, we therefore cannot release it in the same way.

**Comment by Gitoffthelawn** [comment]
@kewisch Thanks for your reply!

What is the deployment schedule/pattern for Firefox installations that are using the release build (of Firefox)?

To the end users, it appears almost random, but I imagine it's not random at all (well, hopefully not!). :)
